micronaut:
  application:
    name: leitornfe
netty:
  default:
    allocator:
      max-order: 3

ELASTIC_HOST: "http://localhost:9200"

endpoints:
  health:
    elasticsearch:
      enabled: true


jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true